# -*- coding: utf-8 -*-
#!/usr/bin/python3



# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# answer = 
def sum_even_valued(max):
    first = 1
    second = 2
    last_item = second
    item = first + second
    sum = second
    while item < max:
        if item % 2 == 0:
            sum = sum + item
        item = item + last_item
        last_item = item - last_item
    return sum
        
result = sum_even_valued(10)
print('result=%s' % result)
result = sum_even_valued(4000000)
print('result=%s' % result)